package com.hbm.lib;

import com.hbm.Tags;
import com.hbm.handler.GunConfiguration;
import net.minecraft.util.ResourceLocation;
import net.minecraft.util.SoundEvent;
import net.minecraftforge.fml.common.registry.ForgeRegistries;

import java.util.ArrayList;
import java.util.List;

public final class HBMSoundHandler {

    public static List<SoundEvent> ALL_SOUNDS = new ArrayList<>();

    public static SoundEvent assemblerOperate;
    public static SoundEvent fel;
    public static SoundEvent fensuHum;
    public static SoundEvent hephaestusRunning;
    public static SoundEvent siloopen;
    public static SoundEvent siloclose;
    public static SoundEvent pressOperate;
    public static SoundEvent laserBang;
    public static SoundEvent blockDebris;
    public static SoundEvent rbmkLid;
    public static SoundEvent syringeUse;
    public static SoundEvent sparkShoot;
    public static SoundEvent b92Reload;
    public static SoundEvent techBleep;
    public static SoundEvent techBoop;
    public static SoundEvent hornNearSingle;
    public static SoundEvent hornNearDual;
    public static SoundEvent largeTurbineRunning;
    public static SoundEvent engine;
    public static SoundEvent hornFarSingle;
    public static SoundEvent hornFarDual;
    public static SoundEvent reactorLoop;
    public static SoundEvent reactorStart;
    public static SoundEvent reactorStop;
    public static SoundEvent chemplantOperate;
    public static SoundEvent chemicalPlant;
    public static SoundEvent potatOSRandom;
    public static SoundEvent weaponSpinDown;
    public static SoundEvent weaponSpinUp;
    public static SoundEvent sawShoot;
    public static SoundEvent rpgShoot;
    public static SoundEvent rifleShoot;
    public static SoundEvent defabShoot;
    public static SoundEvent flamethrowerIgnite;
    public static SoundEvent flamethrowerShoot;
    public static SoundEvent tauShoot;
    public static SoundEvent oldExplosion;
    public static SoundEvent nuclearExplosion;
    public static SoundEvent ciwsSpindown;
    public static SoundEvent ciwsSpinup;
    public static SoundEvent ciwsFiringLoop;
    public static SoundEvent reloadTurret;
    public static SoundEvent warnOverspeed;
    public static SoundEvent planeShotDown;
    public static SoundEvent bombWhistle;
    public static SoundEvent mortarWhistle;
    public static SoundEvent planeCrash;
    public static SoundEvent missileTakeoff;
    public static SoundEvent bomberSmallLoop;
    public static SoundEvent bomberLoop;
    public static SoundEvent stingerLockon;
    public static SoundEvent trainHorn;
    public static SoundEvent bombDet;
    public static SoundEvent rumble;
    public static SoundEvent pipeFail;
    public static SoundEvent lpwstart;
    public static SoundEvent lpwstop;
    public static SoundEvent lpwloop;
    public static SoundEvent htrstart;
    public static SoundEvent htrstop;
    public static SoundEvent htrloop;
    public static SoundEvent rocketIgnition;
    public static SoundEvent rocketFlyLight;
    public static SoundEvent rocketFlyHeavy;
    public static SoundEvent rocketTakeoff;
    public static SoundEvent silencerShoot;
    public static SoundEvent rpgReload;
    public static SoundEvent reloadGrenade;
    public static SoundEvent reloadShotgun;
    public static SoundEvent reloadMag;
    public static SoundEvent reloadRifle;
    public static SoundEvent reloadRevolver;
    public static SoundEvent boatWeapon;
    public static SoundEvent ricochet;
    public static SoundEvent grenadeBounce;
    public static SoundEvent boiler;
    public static SoundEvent boiler_groan1;
    public static SoundEvent boiler_groan2;
    public static SoundEvent boiler_groan3;
    public static SoundEvent alarmGambit;
    public static SoundEvent pyroOperate;
    public static SoundEvent electricHum;
    public static SoundEvent revolverShoot;
    public static SoundEvent heavyShoot;
    public static SoundEvent schrabidiumShoot;
    public static SoundEvent revolverShootAlt;
    public static SoundEvent hkShoot;
    public static SoundEvent shotgunShoot;
    public static SoundEvent shottyShoot;
    public static SoundEvent uziShoot;
    public static SoundEvent calShoot;
    public static SoundEvent lacunaeShoot;
    public static SoundEvent fatmanShoot;
    public static SoundEvent osiprShoot;
    public static SoundEvent zomgShoot;
    public static SoundEvent jetpackTank;
    public static SoundEvent nullTau;
    public static SoundEvent nullRadar;
    public static SoundEvent immolatorIgnite;
    public static SoundEvent immolatorShoot;
    public static SoundEvent defabSpinup;
    public static SoundEvent cryolatorShoot;
    public static SoundEvent singFlyby;
    public static SoundEvent osiprCharging;
    public static SoundEvent leverActionReload;
    public static SoundEvent follyOpen;
    public static SoundEvent follyReload;
    public static SoundEvent follyClose;
    public static SoundEvent follyFire;
    public static SoundEvent follyBuzzer;
    public static SoundEvent follyAquired;
    public static SoundEvent chopperDrop;
    public static SoundEvent crateBreak;
    public static SoundEvent itemUnpack;
    public static SoundEvent centrifugeOperate;
    public static SoundEvent buttonNo;
    public static SoundEvent buttonYes;
    public static SoundEvent railgunFire;
    public static SoundEvent railgunOrientation;
    public static SoundEvent railgunCharge;
    public static SoundEvent shutdown;
    public static SoundEvent broadcast1;
    public static SoundEvent broadcast2;
    public static SoundEvent broadcast3;
    public static SoundEvent geiger1;
    public static SoundEvent geiger2;
    public static SoundEvent geiger3;
    public static SoundEvent geiger4;
    public static SoundEvent geiger5;
    public static SoundEvent geiger6;
    public static SoundEvent voices1;
    public static SoundEvent voices2;
    public static SoundEvent voices3;
    public static SoundEvent voices4;
    public static SoundEvent voices5;
    public static SoundEvent voices6;
    public static SoundEvent voices7;
    public static SoundEvent voices8;
    public static SoundEvent lockOpen;
    public static SoundEvent pinBreak;
    public static SoundEvent pinUnlock;
    public static SoundEvent lockHang;
    public static SoundEvent vaultScrapeNew;
    public static SoundEvent vaultThudNew;
    public static SoundEvent missileAssembly2;
    public static SoundEvent sonarPing;
    public static SoundEvent radawayUse;
    public static SoundEvent gasmaskScrew;
    public static SoundEvent spray;
    public static SoundEvent repair;
    public static SoundEvent nullChopper;
    public static SoundEvent chopperCharge;
    public static SoundEvent nullCrashing;
    public static SoundEvent chopperDamage;
    public static SoundEvent nullMine;
    public static SoundEvent openDoor;
    public static SoundEvent closeDoor;
    public static SoundEvent openC;
    public static SoundEvent closeC;
    public static SoundEvent steamEngineOperate;

    public static SoundEvent explosionSmallNear;
    public static SoundEvent explosionSmallFar;
    public static SoundEvent explosionLargeNear;
    public static SoundEvent explosionLargeFar;
    public static SoundEvent boltgun;
    public static SoundEvent chungusOperate;
    public static SoundEvent bang;
    public static SoundEvent slice;
    public static SoundEvent kaping;
    public static SoundEvent pipePlaced;
    public static SoundEvent tesla;
    public static SoundEvent cybercrab;
    public static SoundEvent osiprReload;
    public static SoundEvent fatmanReload;
    public static SoundEvent soyuzReady;
    public static SoundEvent soyuzTakeOff;
    public static SoundEvent chime;
    public static SoundEvent deagleShoot;
    public static SoundEvent tauChargeLoop;
    public static SoundEvent tauChargeLoop2;
    public static SoundEvent chopperFlyingLoop;
    public static SoundEvent chopperCrashingLoop;
    public static SoundEvent chopperMineLoop;
    public static SoundEvent lacunaeSpinup;
    public static SoundEvent lacunaeSpindown;
    public static SoundEvent teslaShoot;
    public static SoundEvent flamerReload;
    public static SoundEvent stop;
    public static SoundEvent bonk;
    public static SoundEvent glauncher;
    public static SoundEvent hksShoot;
    public static SoundEvent vice;
    public static SoundEvent screm;
    public static SoundEvent upgradePlug;
    public static SoundEvent quadroReload;
    public static SoundEvent fstbmbStart;
    public static SoundEvent fstbmbPing;
    public static SoundEvent sauerGun;
    public static SoundEvent ducc;
    public static SoundEvent whack;
    public static SoundEvent turbofanOperate;
    public static SoundEvent slicer;
    public static SoundEvent megaquacc;
    public static SoundEvent chainsaw;
    public static SoundEvent battery;
    public static SoundEvent rocketFlame;
    public static SoundEvent rocketEngine;
    public static SoundEvent ballsLaser;
    public static SoundEvent dartShoot;
    public static SoundEvent gluonStart;
    public static SoundEvent gluonLoop;
    public static SoundEvent gluonEnd;
    public static SoundEvent gluonHit;
    public static SoundEvent jetpack;
    public static SoundEvent switchmode1;
    public static SoundEvent switchmode2;
    public static SoundEvent mukeExplosion;
    public static SoundEvent explosion_medium;
    public static SoundEvent explosion_tiny;
    public static SoundEvent crucibleStart;
    public static SoundEvent crucibleEnd;
    public static SoundEvent crucibleSwing;
    public static SoundEvent crucibleLoop;
    public static SoundEvent cDeploy;
    public static SoundEvent jsg_reload0;
    public static SoundEvent jsg_reload1;
    public static SoundEvent mob_gib;
    public static SoundEvent blood_splat;
    public static SoundEvent hit_dirt;
    public static SoundEvent hit_metal;
    public static SoundEvent hit_flesh;
    public static SoundEvent vomit;
    public static SoundEvent chekhov_fire;
    public static SoundEvent jeremy_fire;
    public static SoundEvent jeremy_reload;
    public static SoundEvent richard_fire;
    public static SoundEvent howard_fire;
    public static SoundEvent howard_reload;
    public static SoundEvent sentryFire;
    public static SoundEvent sentryLockon;
    public static SoundEvent rbmk_explosion;
    public static SoundEvent rbmk_az5_cover;
    public static SoundEvent chungus_lever;
    public static SoundEvent bobble;
    public static SoundEvent crateOpen;
    public static SoundEvent crateClose;
    public static SoundEvent storageOpen;
    public static SoundEvent storageClose;
    public static SoundEvent turbinegasRunning;
    public static SoundEvent turbinegasShutdown;
    public static SoundEvent turbinegasStartup;
    public static SoundEvent dflash;
    public static SoundEvent cough;
    public static SoundEvent gulp;
    public static SoundEvent groan;
    public static SoundEvent ufoBeam;
    public static SoundEvent ufoBlast;
    public static SoundEvent iGeneratorOperate;
    public static SoundEvent motor;
    public static SoundEvent tubeFwoomp;

    public static SoundEvent transitionSealOpen;
    public static SoundEvent garage;
    public static SoundEvent garage_stop;
    public static SoundEvent door_spinny;
    public static SoundEvent wgh_big_start;
    public static SoundEvent wgh_big_stop;
    public static SoundEvent wgh_start;
    public static SoundEvent wgh_stop;
    public static SoundEvent alarm6;
    public static SoundEvent qe_sliding_shut;
    public static SoundEvent qe_sliding_opened;
    public static SoundEvent qe_sliding_opening;
    public static SoundEvent hatch_open;
    public static SoundEvent sliding_seal_open;
    public static SoundEvent sliding_seal_stop;
    public static SoundEvent revolverCock;
    public static SoundEvent magSmallRemove;
    public static SoundEvent magSmallInsert;
    public static SoundEvent revolverClose;
    public static SoundEvent dryFireClick;
    public static SoundEvent revolverSpin;
    public static SoundEvent leverCock;
    public static SoundEvent openLatch;
    public static SoundEvent magRemove;
    public static SoundEvent magInsert;
    public static SoundEvent pistolCock;
    public static SoundEvent shotgunReload;
    public static SoundEvent insertCanister;
    public static SoundEvent impact;
    public static SoundEvent glReload;
    public static SoundEvent glOpen;
    public static SoundEvent glClose;
    public static SoundEvent flameLoop;
    public static SoundEvent pressureValve;
    public static SoundEvent shotgunCock;
    public static SoundEvent shotgunCockOpen;
    public static SoundEvent shotgunCockClose;
    public static SoundEvent gunWhack;
    public static SoundEvent lockon;
    public static SoundEvent boltOpen;
    public static SoundEvent boltClose;
    public static SoundEvent shredderCycle;
    public static SoundEvent rifleCock;
    public static SoundEvent screw;
    public static SoundEvent insertRocket;
    public static SoundEvent tau;
    public static SoundEvent tauLoop;
    public static SoundEvent fatmanFull;
    public static SoundEvent coilgunReload;
    public static SoundEvent smack;
    public static SoundEvent squeakyToy;
    public static SoundEvent fireSilenced;
    public static SoundEvent fireGreaseGun;
    public static SoundEvent firePistol;
    public static SoundEvent fireBlackPowder;
    public static SoundEvent fireUzi;
    public static SoundEvent fireAberrator;
    public static SoundEvent coilgunShoot;
    public static SoundEvent fireTauRelease;
    public static SoundEvent fireFatman;
    public static SoundEvent fireRifle;
    public static SoundEvent shoot44;
    public static SoundEvent fireShotgun;
    public static SoundEvent loudestNoiseOnEarth;
    public static SoundEvent fireTesla;
    public static SoundEvent fireLaser;
    public static SoundEvent fireShotgunAuto;
    public static SoundEvent fireShotgunAlt;
    public static SoundEvent glShoot;
    public static SoundEvent fireLaserGatling;
    public static SoundEvent fireRifleHeavy;
    public static SoundEvent fireAssault;
    public static SoundEvent fireDisintegration;
    public static SoundEvent fireLaserPistol;
    public static SoundEvent fireStab;
    public static SoundEvent fireGrenade;
    public static SoundEvent fireAmat;
    public static SoundEvent fireExtinguisher;
    public static SoundEvent assemblerStrike;
    public static SoundEvent assemblerStart;
    public static SoundEvent assemblerStop;
    public static SoundEvent meteoriteFallingLoop;
    public static SoundEvent assemblerCut;
    public static SoundEvent fusionReactorRunning;

    public static SoundEvent alarmHatch = registerBypass("alarm.hatch");
    public static SoundEvent alarmAutopilot = registerBypass("alarm.autopilot");
    public static SoundEvent alarmAMSSiren = registerBypass("alarm.amsSiren");
    public static SoundEvent alarmBlastDoor = registerBypass("alarm.blastDoorAlarm");
    public static SoundEvent alarmAPCLoop = registerBypass("alarm.apcLoop");
    public static SoundEvent alarmKlaxon = registerBypass("alarm.klaxon");
    public static SoundEvent alarmFoKlaxonA = registerBypass("alarm.foKlaxonA");
    public static SoundEvent alarmFoKlaxonB = registerBypass("alarm.foKlaxonB");
    public static SoundEvent alarmRegular = registerBypass("alarm.regularSiren");
    public static SoundEvent alarmClassic = registerBypass("alarm.classic");
    public static SoundEvent alarmBank = registerBypass("alarm.bankAlarm");
    public static SoundEvent alarmBeep = registerBypass("alarm.beepSiren");
    public static SoundEvent alarmContainer = registerBypass("alarm.containerAlarm");
    public static SoundEvent alarmSweep = registerBypass("alarm.sweepSiren");
    public static SoundEvent alarmStrider = registerBypass("alarm.striderSiren");
    public static SoundEvent alarmAirRaid = registerBypass("alarm.airRaid");
    public static SoundEvent alarmNostromo = registerBypass("alarm.nostromoSiren");
    public static SoundEvent alarmEas = registerBypass("alarm.easAlarm");
    public static SoundEvent alarmAPCPass = registerBypass("alarm.apcPass");
    public static SoundEvent alarmRazorTrain = registerBypass("alarm.razortrainHorn");
    public static SoundEvent soyuzed = registerBypass("alarm.soyuzed");
    public static SoundEvent metalStep = registerBypass("step.metal");
    public static SoundEvent iron = registerBypass("step.iron");
    public static SoundEvent ironLand = registerBypass("step.iron_land");
    public static SoundEvent ironJump = registerBypass("step.iron_jump");
    public static SoundEvent poweredStep = registerBypass("step.powered");

    public static SoundEvent lambdaCore = registerBypass("music.recordlambdacore");
    public static SoundEvent sectorSweep = registerBypass("music.recordsectorsweep");
    public static SoundEvent vortalCombat = registerBypass("music.recordvortalcombat");
    public static SoundEvent glass = registerBypass("music.transmission");

    public static SoundEvent metalBlock = registerBypass("step.metalBlock");

    public static SoundEvent[] geigerSounds;
    public static SoundEvent[] voiceSounds;
    public static SoundEvent[] boilerGroanSounds;

    /**
     * How to register a sound:
     * 1. Create the sound here, and register in init();
     * 2. add the sound to sounds.json.
     * IMPORTANT: suppose you create an entry like this:
     * "block.assembleroperate": {"category": "block", "sounds": [{"name": "hbm:block/assemblerOperate", "stream": false}]},
     * This works, but you must ensure that the .ogg file in src\main\resources\assets\hbm\sounds\block is in lowercase.
     * In other words, there must be an assembleroperate.ogg under that directory. assemblerOperate.ogg won't work!
     */
    public static void init() {

        explosionSmallNear = register("weapon.explosion_small_near");
        explosionSmallFar  = register("weapon.explosion_small_far");
        explosionLargeNear = register("weapon.explosion_large_near");
        explosionLargeFar  = register("weapon.explosion_large_far");
        assemblerOperate = register("block.assembleroperate");
        fel = register("block.fel");
        fensuHum = register("block.fensuHum");
        hephaestusRunning = register("block.hephaestusRunning");
        meteoriteFallingLoop = register("entity.meteoriteFallingLoop");
        pressOperate = register("block.pressoperate");
        laserBang = register("weapon.laserBang");
        blockDebris = register("block.debris");
        rbmkLid = register("block.rbmkLid");
        syringeUse = register("item.syringe");
        sparkShoot = register("weapon.sparkShoot");
        b92Reload = register("weapon.b92Reload");
        techBleep = register("item.techBleep");
        techBoop = register("item.techBoop");
        hornNearSingle = register("block.hornNearSingle");
        largeTurbineRunning = register("block.largeTurbine");
        engine = register("block.engine");
        hornNearDual = register("block.hornNearDual");
        hornFarSingle = register("block.hornFarSingle");
        hornFarDual = register("block.hornFarDual");
        reactorLoop = register("block.reactorLoop");
        reactorStart = register("block.reactorStart");
        reactorStop = register("block.reactorStop");
        chemplantOperate = register("block.chemplantOperate");
        chemicalPlant = register("block.chemicalPlant");
        potatOSRandom = register("potatos.random");
        weaponSpinDown = register("weapon.spindown");
        weaponSpinUp = register("weapon.spinup");
        sawShoot = register("weapon.sawShoot");
        rpgShoot = register("weapon.rpgShoot");
        reloadTurret = register("weapon.reloadTurret");
        rifleShoot = register("weapon.rifleShoot");
        defabShoot = register("weapon.defabShoot");
        flamethrowerIgnite = register("weapon.flamethrowerIgnite");
        flamethrowerShoot = register("weapon.flamethrowerShoot");
        tauShoot = register("weapon.tauShoot");
        oldExplosion = register("entity.oldExplosion");
        nuclearExplosion = register("weapon.nuclearExplosion");
        boiler = register("block.boiler");
        boiler_groan1 = register("block.boilerGroan0");
        boiler_groan2 = register("block.boilerGroan1");
        boiler_groan3 = register("block.boilerGroan2");
        ciwsSpindown = register("weapon.ciwsSpindown");
        ciwsSpinup = register("weapon.ciwsSpinup");
        ciwsFiringLoop = register("weapon.ciwsFiringLoop");
        warnOverspeed = register("block.warnOverspeed");
        planeShotDown = register("entity.planeShotDown");
        bombWhistle = register("entity.bombWhistle");
        mortarWhistle = register("entity.mortarWhistle");
        planeCrash = register("entity.planeCrash");
        missileTakeoff = register("weapon.missileTakeOff");
        bomberSmallLoop = register("entity.bomberSmallLoop");
        bomberLoop = register("entity.bomberLoop");
        stingerLockon = register("weapon.stingerLockOn");
        trainHorn = register("alarm.trainhorn");
        bombDet = register("entity.bombDet");
        rumble = register("misc.rumble");
        pipeFail = register("entity.pipefail");
        lpwstart = register("misc.lpwstart");
        lpwstop = register("misc.lpwstop");
        lpwloop = register("misc.lpwloop");
        htrstart = register("misc.htrstart");
        htrstop = register("misc.htrstop");
        htrloop = register("misc.htrloop");
        rocketTakeoff = register("entity.rocketTakeoff");
        rocketIgnition = register("entity.rocketIgnition");
        rocketFlyLight = register("entity.rocketFlyLight");
        rocketFlyHeavy = register("entity.rocketFlyHeavy");
        silencerShoot = register("weapon.silencerShoot");
        GunConfiguration.RSOUND_LAUNCHER = rpgReload = register("weapon.rpgReload");
        GunConfiguration.RSOUND_GRENADE = reloadGrenade = register("weapon.hkReload");
        GunConfiguration.RSOUND_SHOTGUN = reloadShotgun = register("weapon.shotgunReload");
        GunConfiguration.RSOUND_MAG = reloadMag = register("weapon.magReload");
        GunConfiguration.RSOUND_RIFLE = reloadRifle = register("");
        GunConfiguration.RSOUND_REVOLVER = reloadRevolver = register("weapon.revolverReload");
        GunConfiguration.RSOUND_FATMAN = fatmanReload = register("weapon.fatmanReload");
        boatWeapon = register("weapon.boat");
        ricochet = register("weapon.ricochet");
        grenadeBounce = register("weapon.gBounce");
        alarmGambit = register("alarm.gambit");
        revolverShoot = register("weapon.revolverShoot");
        heavyShoot = register("weapon.heavyShoot");
        schrabidiumShoot = register("weapon.schrabidiumShoot");
        revolverShootAlt = register("weapon.revolverShootAlt");
        hkShoot = register("weapon.hkShoot");
        shotgunShoot = register("weapon.shotgunShoot");
        shottyShoot = register("weapon.shottyShoot");
        uziShoot = register("weapon.uziShoot");
        calShoot = register("weapon.calShoot");
        lacunaeShoot = register("weapon.lacunaeShoot");
        fatmanShoot = register("weapon.fatmanShoot");
        osiprShoot = register("weapon.osiprShoot");
        zomgShoot = register("weapon.zomgShoot");
        jetpackTank = register("item.jetpackTank");
        switchmode1 = register("weapon.switchmode1");
        switchmode2 = register("weapon.switchmode2");
        nullTau = register("misc.nullTau");
        nullRadar = register("misc.nullRadar");
        immolatorIgnite = register("weapon.immolatorIgnite");
        immolatorShoot = register("weapon.immolatorShoot");
        defabSpinup = register("weapon.defabSpinup");
        cryolatorShoot = register("weapon.cryolatorShoot");
        singFlyby = register("weapon.singFlyby");
        osiprCharging = register("weapon.osiprCharging");
        leverActionReload = register("weapon.leverActionReload");
        follyOpen = register("weapon.follyOpen");
        follyReload = register("weapon.follyReload");
        follyClose = register("weapon.follyClose");
        follyFire = register("weapon.follyFire");
        follyBuzzer = register("weapon.follyBuzzer");
        follyAquired = register("weapon.follyAquired");
        chopperDrop = register("entity.chopperDrop");
        pyroOperate = register("block.pyroOperate");
        electricHum = register("block.electricHum");
        crateBreak = register("block.crateBreak");
        itemUnpack = register("item.unpack");
        centrifugeOperate = register("block.centrifugeOperate");
        buttonNo = register("block.buttonNo");
        buttonYes = register("block.buttonYes");
        railgunFire = register("block.railgunFire");
        railgunOrientation = register("block.railgunOrientation");
        railgunCharge = register("block.railgunCharge");
        shutdown = register("block.shutdown");
        broadcast1 = register("block.broadcast1");
        broadcast2 = register("block.broadcast2");
        broadcast3 = register("block.broadcast3");
        geiger1 = register("item.geiger1");
        geiger2 = register("item.geiger2");
        geiger3 = register("item.geiger3");
        geiger4 = register("item.geiger4");
        geiger5 = register("item.geiger5");
        geiger6 = register("item.geiger6");
        voices1 = register("item.voices1");
        voices2 = register("item.voices2");
        voices3 = register("item.voices3");
        voices4 = register("item.voices4");
        voices5 = register("item.voices5");
        voices6 = register("item.voices6");
        voices7 = register("item.voices7");
        voices8 = register("item.voices8");
        lockOpen = register("block.lockOpen");
        pinBreak = register("item.pinBreak");
        pinUnlock = register("item.pinUnlock");
        lockHang = register("block.lockHang");
        vaultScrapeNew = register("block.vaultScrapeNew");
        vaultThudNew = register("block.vaultThudNew");
        missileAssembly2 = register("block.missileAssembly2");
        sonarPing = register("block.sonarPing");
        radawayUse = register("item.radaway");
        gasmaskScrew = register("item.gasmaskScrew");
        spray = register("item.spray");
        repair = register("item.repair");
        nullChopper = register("misc.nullChopper");
        chopperCharge = register("entity.chopperCharge");
        nullCrashing = register("misc.nullCrashing");
        chopperDamage = register("entity.chopperDamage");
        nullMine = register("misc.nullMine");
        openDoor = register("block.openDoor");
        closeDoor = register("block.closeDoor");
        openC = register("block.openc");
        closeC = register("block.closec");
        steamEngineOperate = register("block.steamEngineOperate");
        boltgun = register("item.boltgun");
        bang = register("weapon.bang");
        slice = register("weapon.slice");
        kaping = register("weapon.kapeng");
        pipePlaced = register("block.pipePlaced");
        tesla = register("weapon.tesla");
        cybercrab = register("entity.cybercrab");
        osiprReload = register("weapon.osiprReload");
        soyuzReady = register("block.soyuzReady");
        soyuzTakeOff = register("entity.soyuzTakeoff");
        chime = register("alarm.chime");
        deagleShoot = register("weapon.deagleShoot");
        tauChargeLoop2 = register("weapon.tauChargeLoop2");
        chopperFlyingLoop = register("entity.chopperFlyingLoop");
        chopperCrashingLoop = register("entity.chopperCrashingLoop");
        chopperMineLoop = register("entity.chopperMineLoop");
        lacunaeSpinup = register("weapon.lacunaeSpinup");
        lacunaeSpindown = register("weapon.lacunaeSpindown");
        teslaShoot = register("weapon.teslaShoot");
        flamerReload = register("weapon.flamerReload");
        stop = register("weapon.stop");
        bonk = register("weapon.bonk");
        glauncher = register("weapon.glauncher");
        hksShoot = register("weapon.hksShoot");
        vice = register("item.vice");
        screm = register("block.screm");
        upgradePlug = register("item.upgradePlug");
        tauChargeLoop = register("weapon.tauChargeLoop");
        quadroReload = register("weapon.quadroReload");
        fstbmbStart = register("weapon.fstbmbStart");
        fstbmbPing = register("weapon.fstbmbPing");
        sauerGun = register("weapon.sauergun");
        ducc = register("entity.ducc");
        whack = register("weapon.whack");
        turbofanOperate = register("block.turbofanOperate");
        slicer = register("entity.slicer");
        megaquacc = register("entity.megaquacc");
        chainsaw = register("weapon.chainsaw");
        battery = register("item.battery");
        rocketFlame = register("weapon.rocketFlame");
        rocketEngine = register("entity.rocketEngine");
        ballsLaser = register("weapon.ballsLaser");
        dartShoot = register("weapon.dartShoot");
        gluonStart = register("weapon.gluonstart");
        gluonLoop = register("weapon.gluonloop");
        gluonEnd = register("weapon.gluonend");
        gluonHit = register("weapon.gluonhit");
        jetpack = register("weapon.jetpack");
        mukeExplosion = register("weapon.mukeExplosion");
        explosion_medium = register("weapon.explosion_medium");
        explosion_tiny = register("weapon.explosion_tiny");
        crucibleStart = register("weapon.crucible_start");
        crucibleEnd = register("weapon.crucible_end");
        crucibleSwing = register("weapon.crucible_swing");
        crucibleLoop = register("weapon.crucible_loop");
        cDeploy = register("weapon.cDeploy");
        jsg_reload0 = register("weapon.jsg_reload0");
        jsg_reload1 = register("weapon.jsg_reload1");
        mob_gib = register("weapon.mob_gib");
        blood_splat = register("weapon.blood_splat");
        hit_dirt = register("weapon.hit_dirt");
        hit_metal = register("weapon.hit_metal");
        hit_flesh = register("weapon.hit_flesh");
        vomit = register("entity.vomit");
        chekhov_fire = register("turret.chekhov_fire");
        jeremy_fire = register("turret.jeremy_fire");
        jeremy_reload = register("turret.jeremy_reload");
        richard_fire = register("turret.richard_fire");
        howard_fire = register("turret.howard_fire");
        howard_reload = register("turret.howard_reload");
        sentryFire = register("turret.sentry_fire");
        sentryLockon = register("turret.sentry_lockon");
        rbmk_explosion = register("block.rbmk_explosion");
        rbmk_az5_cover = register("block.rbmk_az5_cover");
        bobble = register("block.bobble");
        crateOpen = register("block.crateOpen");
        crateClose = register("block.crateClose");
        storageOpen = register("block.storageOpen");
        storageClose = register("block.storageClose");
        turbinegasRunning = register("block.turbinegasRunning");
        turbinegasShutdown = register("block.turbinegasShutdown");
        turbinegasStartup = register("block.turbinegasStartup");
        chungus_lever = register("block.chungusLever");
        chungusOperate = register("block.chungusTurbineRunning");
        dflash = register("weapon.dFlash");
        cough = register("player.cough");
        gulp = register("player.gulp");
        groan = register("player.groan");
        ufoBeam = register("entity.ufoBeam");
        ufoBlast = register("entity.ufoBlast");
        iGeneratorOperate = register("block.igeneratoroperate");
        transitionSealOpen = register("block.door.transitionseal");
        siloopen = register("block.door.siloopen");
        siloclose = register("block.door.siloclose");
        garage = register("block.door.garage");
        garage_stop = register("block.door.garagestop");
        door_spinny = register("block.door.lever");
        wgh_big_start = register("block.door.wgh_big_start");
        wgh_big_stop = register("block.door.wgh_big_stop");
        wgh_start = register("block.door.wgh_start");
        wgh_stop = register("block.door.wgh_stop");
        alarm6 = register("block.door.alarm6");
        qe_sliding_shut = register("block.door.qe_sliding_shut");
        qe_sliding_opened = register("block.door.qe_sliding_opened");
        qe_sliding_opening = register("block.door.qe_sliding_opening");
        hatch_open = register("block.door.hatch_open");
        sliding_seal_open = register("block.door.sliding_seal_open");
        sliding_seal_stop = register("block.door.sliding_seal_stop");
        revolverCock = register("weapon.reload.revolverCock");
        magSmallRemove = register("weapon.reload.magSmallRemove");
        magSmallInsert = register("weapon.reload.magSmallInsert");
        revolverClose = register("weapon.reload.revolverClose");
        dryFireClick = register("weapon.reload.dryFireClick");
        revolverSpin = register("weapon.reload.revolverSpin");
        leverCock = register("weapon.reload.leverCock");
        openLatch = register("weapon.reload.openLatch");
        magRemove = register("weapon.reload.magRemove");
        magInsert = register("weapon.reload.magInsert");
        pistolCock = register("weapon.reload.pistolCock");
        shotgunReload = register("weapon.reload.shotgunReload");
        insertCanister = register("weapon.reload.insertCanister");
        impact = register("weapon.reload.impact");
        glReload = register("weapon.glReload");
        glOpen = register("weapon.glOpen");
        glClose = register("weapon.glClose");
        flameLoop = register("weapon.fire.flameLoop");
        pressureValve = register("weapon.reload.pressureValve");
        shotgunCockOpen = register("weapon.reload.shotgunCockOpen");
        shotgunCock = register("weapon.reload.shotgunCock");
        shotgunCockClose = register("weapon.reload.shotgunCockClose");
        gunWhack = register("weapon.foley.gunWhack");
        lockon = register("weapon.fire.lockon");
        boltOpen = register("weapon.reload.boltOpen");
        boltClose = register("weapon.reload.boltClose");
        shredderCycle = register("weapon.fire.shredderCycle");
        rifleCock = register("weapon.reload.rifleCock");
        screw = register("weapon.reload.screw");
        insertRocket = register("weapon.reload.insertRocket");
        tau = register("weapon.fire.tau");
        tauLoop = register("weapon.fire.tauLoop");
        fatmanFull = register("weapon.reload.fatmanFull");
        coilgunReload = register("weapon.coilgunReload");
        smack = register("weapon.fire.smack");
        squeakyToy = register("block.squeakyToy");
        motor = register("block.motor");
        fireSilenced = register("weapon.fire.silenced");
        firePistol = register("weapon.fire.pistol");
        fireBlackPowder = register("weapon.fire.blackPowder");
        fireUzi = register("weapon.fire.uzi");
        fireGreaseGun = register("weapon.fire.greaseGun");
        fireAberrator = register("weapon.fire.aberrator");
        coilgunShoot = register("weapon.coilgunShoot");
        fireTauRelease = register("weapon.fire.tauRelease");
        fireFatman = register("weapon.fire.fatman");
        fireRifle = register("weapon.fire.rifle");
        shoot44 = register("weapon.44Shoot");
        fireShotgun = register("weapon.fire.shotgun");
        loudestNoiseOnEarth = register("weapon.fire.loudestNoiseOnEarth");
        fireTesla = register("weapon.fire.tesla");
        fireLaser = register("weapon.fire.laser");
        fireShotgunAuto = register("weapon.fire.shotgunAlt");
        fireShotgunAlt = register("weapon.fire.shotgunAuto");
        glShoot = register("weapon.glShoot");
        fireLaserGatling = register("weapon.fire.laserGatling");
        fireRifleHeavy = register("weapon.fire.rifleHeavy");
        fireAssault = register("weapon.fire.assault");
        fireDisintegration = register("weapon.fire.disintegration");
        fireLaserPistol = register("weapon.fire.laserPistol");
        fireStab = register("weapon.fire.stab");
        fireGrenade = register("weapon.fire.grenade");
        fireAmat = register("weapon.fire.amat");
        fireExtinguisher = register("weapon.extinguisher");
        assemblerStrike = register("block.assemblerStrike");
        assemblerStart = register("block.assemblerStart");
        assemblerStop = register("block.assemblerStop");
        assemblerCut = register("block.assemblerCut");
        tubeFwoomp = register("weapon.reload.tubeFwoomp");
        fusionReactorRunning = register("block.fusionReactorRunning");

        geigerSounds = new SoundEvent[]{geiger1, geiger2, geiger3, geiger4, geiger5, geiger6};
        voiceSounds = new SoundEvent[]{voices1, voices2, voices3, voices4, voices5, voices6, voices7, voices8};
        boilerGroanSounds = new SoundEvent[]{boiler_groan1, boiler_groan2, boiler_groan3};
    }

    public static SoundEvent register(String name) {
        SoundEvent e = new SoundEvent(new ResourceLocation(Tags.MODID, name));
        e.setRegistryName(name);
        ALL_SOUNDS.add(e);
        return e;
    }

    public static SoundEvent registerBypass(String name) {
        SoundEvent e = new SoundEvent(new ResourceLocation(Tags.MODID, name));
        e.setRegistryName(name);
        ForgeRegistries.SOUND_EVENTS.register(e);
        return e;
    }

}
